// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	videodemo "github.com/gitgou/simple_douyin/kitex_gen/videodemo"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, Req *videodemo.FeedRequest, callOptions ...callopt.Option) (r *videodemo.FeedResponse, err error)
	Publish(ctx context.Context, Req *videodemo.PublishRequest, callOptions ...callopt.Option) (r *videodemo.PublishResponse, err error)
	PublishList(ctx context.Context, Req *videodemo.PublishListRequest, callOptions ...callopt.Option) (r *videodemo.PublishListResponse, err error)
	GetVideoList(ctx context.Context, Req *videodemo.GetVideoListRequest, callOptions ...callopt.Option) (r *videodemo.GetVideoListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, Req *videodemo.FeedRequest, callOptions ...callopt.Option) (r *videodemo.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, Req)
}

func (p *kVideoServiceClient) Publish(ctx context.Context, Req *videodemo.PublishRequest, callOptions ...callopt.Option) (r *videodemo.PublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Publish(ctx, Req)
}

func (p *kVideoServiceClient) PublishList(ctx context.Context, Req *videodemo.PublishListRequest, callOptions ...callopt.Option) (r *videodemo.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, Req)
}

func (p *kVideoServiceClient) GetVideoList(ctx context.Context, Req *videodemo.GetVideoListRequest, callOptions ...callopt.Option) (r *videodemo.GetVideoListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoList(ctx, Req)
}
