// Code generated by Kitex v0.4.4. DO NOT EDIT.
package chatservice

import (
	server "github.com/cloudwego/kitex/server"
	chatdemo "github.com/gitgou/simple_douyin/kitex_gen/chatdemo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler chatdemo.ChatService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
